version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qnf_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__WriteConnection=Host=pg_master;Port=5432;Database=QuebraNuncaWrite;Username=admin;Password=admin
      - ConnectionStrings__ReadConnection=Host=pg_replica;Port=5432;Database=QuebraNuncaRead;Username=admin;Password=admin
    ports:
      - "5000:80"
    depends_on:
      - pg_master
      - pg_replica

  pg_master:
    build: ./docker/postgres-replication/master
    container_name: pg_master
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: QuebraNuncaWrite
    ports:
      - "5433:5432"
    volumes:
      - pg_master_data:/var/lib/postgresql/data

  pg_replica:
    build: ./docker/postgres-replication/replica
    container_name: pg_replica
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: QuebraNuncaRead
    ports:
      - "5434:5432"
    depends_on:
      - pg_master
    volumes:
      - pg_replica_data:/var/lib/postgresql/data

volumes:
  pg_master_data:
  pg_replica_data:
