// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QNF.Plataforma.Infrastructure.Data;

#nullable disable

namespace QNF.Plataforma.Infrastructure.Migrations.WriteMigrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20250703204818_InitialWriteSchema")]
    partial class InitialWriteSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QNF.Plataforma.Core.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LeftPlayerTeamA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LeftPlayerTeamB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PointsTeamA")
                        .HasColumnType("integer");

                    b.Property<int>("PointsTeamB")
                        .HasColumnType("integer");

                    b.Property<string>("RightPlayerTeamA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RightPlayerTeamB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
